//! Token Collector - reads Claude Code JSONL session files and extracts usage data
//!
//! This module handles:
//! - Walking ~/.claude/projects/**/*.jsonl to find session files
//! - Parsing usage blocks from assistant messages
//! - Tracking per-model token usage by type

use chrono::{Datelike, DateTime, Timelike, Utc};
use chrono_tz::US::Eastern;
use glob::glob;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs::{self, OpenOptions};
use std::io::{self, BufReader, BufWriter, Read, Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use thiserror::Error;

/// Errors that can occur during collection
#[derive(Debug, Error)]
pub enum CollectorError {
    #[error("Glob pattern error: {0}")]
    GlobPattern(String),

    #[error("IO error: {0}")]
    Io(#[from] io::Error),

    #[error("JSON error: {0}")]
    Json(#[from] serde_json::Error),
}

pub type Result<T> = std::result::Result<T, CollectorError>;

/// Usage record extracted from a Claude Code JSONL assistant message
///
/// Contains token counts for all five token types used in Claude API pricing:
/// - Input tokens: prompt tokens sent to the model
/// - Output tokens: tokens generated by the model
/// - Cache read tokens: cached prompt tokens read
/// - Cache write (5m) tokens: prompt tokens written to 5-minute cache
/// - Cache write (1h) tokens: prompt tokens written to 1-hour cache
#[derive(Debug, Clone, PartialEq)]
pub struct UsageRecord {
    /// Input prompt tokens
    pub input_tokens: u64,

    /// Output generation tokens
    pub output_tokens: u64,

    /// Cached prompt tokens that were read from cache
    pub cache_read_tokens: u64,

    /// Prompt tokens written to 5-minute ephemeral cache
    pub cache_write_5m_tokens: u64,

    /// Prompt tokens written to 1-hour ephemeral cache
    pub cache_write_1h_tokens: u64,

    /// Model identifier (e.g., "claude-sonnet-4-20250514")
    pub model: String,

    /// Session identifier (extracted from JSONL file path)
    pub session: String,
}

impl UsageRecord {
    /// Create a new zero-initialized UsageRecord
    pub fn zero(model: String, session: String) -> Self {
        Self {
            input_tokens: 0,
            output_tokens: 0,
            cache_read_tokens: 0,
            cache_write_5m_tokens: 0,
            cache_write_1h_tokens: 0,
            model,
            session,
        }
    }

    /// Get the total tokens used (all types combined)
    pub fn total_tokens(&self) -> u64 {
        self.input_tokens
            + self.output_tokens
            + self.cache_read_tokens
            + self.cache_write_5m_tokens
            + self.cache_write_1h_tokens
    }

    /// Check if this is a zero record (no tokens used)
    pub fn is_zero(&self) -> bool {
        self.total_tokens() == 0
    }
}

/// Raw usage block from a Claude API response
#[derive(Debug, Deserialize)]
pub struct ApiUsage {
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_creation_input_tokens: Option<u64>,
    pub cache_read_input_tokens: Option<u64>,
    pub cache_creation: Option<CacheCreation>,
}

/// Cache creation breakdown (nested in usage block)
#[derive(Debug, Deserialize)]
pub struct CacheCreation {
    pub ephemeral_5m_input_tokens: Option<u64>,
    pub ephemeral_1h_input_tokens: Option<u64>,
}

/// Assistant message from Claude Code JSONL
#[derive(Debug, Deserialize)]
pub struct AssistantMessage {
    pub usage: Option<ApiUsage>,
    pub model: Option<String>,
}

/// JSONL line (can be various message types)
#[derive(Debug, Deserialize)]
pub struct JsonlLine {
    #[serde(rename = "type")]
    pub msg_type: Option<String>,
    pub message: Option<AssistantMessage>,
}

/// Discover all JSONL files under a base directory
///
/// Walks `base/**/*.jsonl` using glob and returns a sorted list of paths.
pub fn discover_jsonl_files(base: &Path) -> Vec<PathBuf> {
    let pattern = base
        .join("**")
        .join("*.jsonl")
        .to_string_lossy()
        .into_owned();

    let paths = match glob(&pattern) {
        Ok(p) => p,
        Err(e) => {
            log::warn!("Invalid glob pattern '{}': {}", pattern, e);
            return Vec::new();
        }
    };

    let mut files: Vec<PathBuf> = paths.filter_map(|entry| entry.ok()).collect();
    files.sort();
    files
}

/// Persistent store for file read cursors
///
/// Tracks the byte offset for each JSONL file to enable incremental reading.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct CursorStore {
    cursors: HashMap<PathBuf, u64>,
}

impl CursorStore {
    /// Load cursor store from a JSON file
    ///
    /// Returns an empty CursorStore if the file doesn't exist.
    pub fn load(path: &Path) -> Result<Self> {
        if !path.exists() {
            return Ok(Self::default());
        }

        let file = fs::File::open(path)?;
        let reader = BufReader::new(file);
        let store: Self = serde_json::from_reader(reader)?;
        Ok(store)
    }

    /// Save cursor store to a JSON file atomically
    ///
    /// Writes to a .tmp file first, then renames to the final path.
    pub fn save(&self, path: &Path) -> Result<()> {
        // Ensure parent directory exists
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        let tmp_path = path.with_extension("tmp");

        // Write to temp file
        {
            let file = fs::File::create(&tmp_path)?;
            let writer = BufWriter::new(file);
            serde_json::to_writer_pretty(writer, self)?;
        }

        // Atomic rename
        fs::rename(&tmp_path, path)?;

        Ok(())
    }

    /// Get the stored offset for a file
    ///
    /// Returns 0 if the file is not in the store.
    pub fn get_offset(&self, file: &Path) -> u64 {
        self.cursors.get(file).copied().unwrap_or(0)
    }

    /// Set the offset for a file
    pub fn set_offset(&mut self, file: PathBuf, offset: u64) {
        self.cursors.insert(file, offset);
    }
}

/// Extract model identifier from a message JSON object
///
/// Primary: reads `model` field from the message JSON object.
/// Fallback: returns "unknown" if the field is missing or null.
pub fn extract_model(message_json: serde_json::Value) -> String {
    message_json
        .get("model")
        .and_then(|v| v.as_str())
        .map(|s| s.to_string())
        .unwrap_or_else(|| "unknown".to_string())
}

/// Extract session ID from a JSONL file path
///
/// Returns the filename stem (without .jsonl extension).
/// Example: `/home/user/.claude/projects/foo/abc123.jsonl` -> `abc123`
pub fn extract_session_id(jsonl_path: &Path) -> String {
    jsonl_path
        .file_stem()
        .and_then(|stem| stem.to_str())
        .map(|s| s.to_string())
        .unwrap_or_else(|| "unknown".to_string())
}

/// Infer model from path hints
///
/// Checks if the path contains model name hints (e.g., directory with "sonnet" or "opus").
/// Returns None for generic paths without model hints.
pub fn infer_model_from_path(jsonl_path: &Path) -> Option<String> {
    let path_str = jsonl_path.to_string_lossy().to_lowercase();

    // Check for common model identifiers in path
    if path_str.contains("opus") {
        // Could refine to specific opus version if path contains version info
        Some("claude-opus".to_string())
    } else if path_str.contains("sonnet") {
        Some("claude-sonnet".to_string())
    } else if path_str.contains("haiku") {
        Some("claude-haiku".to_string())
    } else {
        None
    }
}

/// Parse a usage block from a JSONL line into a UsageRecord
///
/// Extracts token counts, model, and session from the JSON structure.
pub fn parse_usage_block(line: &JsonlLine, jsonl_path: &Path) -> Option<UsageRecord> {
    // Only process assistant messages with usage data
    let message = line.message.as_ref()?;
    let usage = message.usage.as_ref()?;

    // Extract model: prefer message-level model, fallback to path inference, then "unknown"
    let model = message.model.clone().unwrap_or_else(|| {
        infer_model_from_path(jsonl_path).unwrap_or_else(|| "unknown".to_string())
    });

    // Extract session ID from file path
    let session = extract_session_id(jsonl_path);

    // Extract cache write tokens with 5m/1h breakdown
    let (cache_write_5m, cache_write_1h) = match &usage.cache_creation {
        Some(cc) => (
            cc.ephemeral_5m_input_tokens.unwrap_or(0),
            cc.ephemeral_1h_input_tokens.unwrap_or(0),
        ),
        None => {
            // Legacy format: cache_creation_input_tokens without breakdown
            // Treat all as 5m (conservative assumption)
            (usage.cache_creation_input_tokens.unwrap_or(0), 0)
        }
    };

    Some(UsageRecord {
        input_tokens: usage.input_tokens,
        output_tokens: usage.output_tokens,
        cache_read_tokens: usage.cache_read_input_tokens.unwrap_or(0),
        cache_write_5m_tokens: cache_write_5m,
        cache_write_1h_tokens: cache_write_1h,
        model,
        session,
    })
}

/// Read new lines from a JSONL file since the last cursor position
///
/// Seeks to the stored byte offset and reads all content to EOF.
/// If the file has shrunk (log rotation), resets the cursor to 0 and logs a warning.
pub fn read_new_lines(path: &Path, cursor: &mut CursorStore) -> Result<Vec<String>> {
    let stored_offset = cursor.get_offset(path);
    let mut file = fs::File::open(path)?;
    let file_size = file.metadata()?.len();

    let start_offset = if file_size < stored_offset {
        log::warn!(
            "[collector] cursor reset for {} (file shrunk: {} -> {} bytes)",
            path.display(),
            stored_offset,
            file_size
        );
        0
    } else {
        stored_offset
    };

    if start_offset > 0 {
        file.seek(SeekFrom::Start(start_offset))?;
    }

    let mut content = String::new();
    file.read_to_string(&mut content)?;

    let lines: Vec<String> = content
        .split('\n')
        .filter(|line| !line.is_empty())
        .map(|line| line.to_string())
        .collect();

    let new_offset = start_offset + content.len() as u64;
    cursor.set_offset(path.to_path_buf(), new_offset);

    Ok(lines)
}

/// Forecast record for a single usage window
///
/// Captures the current snapshot, ceiling, and projected exhaustion metrics
/// for one of the three Claude Code usage windows (5h, 7d, 7d-sonnet).
#[derive(Debug, Clone, Serialize)]
pub struct WindowRecord {
    /// Record type discriminator (always "w" for window)
    #[serde(rename = "r")]
    pub r: String,

    /// Timestamp of this record
    #[serde(rename = "ts")]
    pub ts: DateTime<Utc>,

    /// Window name: "five_hour", "seven_day", "seven_day_sonnet"
    #[serde(rename = "win")]
    pub win: String,

    /// Peak flag
    #[serde(rename = "pk")]
    pub pk: bool,

    /// Target ceiling from config (e.g. 90.0)
    #[serde(rename = "ceil")]
    pub ceil: f64,

    /// Raw platform utilization %
    #[serde(rename = "snap")]
    pub snap: f64,

    /// Window reset time
    #[serde(rename = "reset")]
    pub reset: DateTime<Utc>,

    /// Pct change this interval (set externally when comparing to previous snapshot)
    #[serde(rename = "delta")]
    pub delta: f64,

    /// Remaining budget: ceil - snap (NOT 100 - snap)
    #[serde(rename = "remain")]
    pub remain: f64,

    /// Hours until window resets
    #[serde(rename = "hrs_left")]
    pub hrs_left: f64,

    /// Fleet burn rate as pct/hr
    #[serde(rename = "fleet_pct_hr")]
    pub fleet_pct_hr: f64,

    /// Hours until exhaustion: remain / fleet_pct_hr
    #[serde(rename = "exh_hrs")]
    pub exh_hrs: f64,

    /// 1 if exh_hrs < hrs_left (will exhaust before window resets)
    #[serde(rename = "cutoff_risk")]
    pub cutoff_risk: u8,

    /// Margin hours: hrs_left - exh_hrs (can be negative)
    #[serde(rename = "margin_hrs")]
    pub margin_hrs: f64,

    /// 1 if this is the most constrained (binding) window
    #[serde(rename = "bind")]
    pub bind: u8,

    /// Safe window in hours (only set on binding window)
    #[serde(rename = "safe_w", skip_serializing_if = "Option::is_none")]
    pub safe_w: Option<u32>,
}

/// Compute a window forecast from current snapshot data
///
/// Derives all forecast fields (remain, hrs_left, exh_hrs, cutoff_risk, margin_hrs)
/// from the raw inputs. The `bind` and `safe_w` fields are left at defaults (0/None)
/// and are set later by `find_binding_window`.
pub fn compute_window_forecast(
    win: &str,
    snap: f64,
    ceil: f64,
    reset: DateTime<Utc>,
    now: DateTime<Utc>,
    fleet_pct_hr: f64,
    pk: bool,
) -> WindowRecord {
    let remain = ceil - snap;
    let hrs_left = (reset - now).num_seconds() as f64 / 3600.0;
    let exh_hrs = if fleet_pct_hr > 0.0 {
        remain / fleet_pct_hr
    } else {
        f64::INFINITY
    };
    let cutoff_risk = if exh_hrs < hrs_left { 1 } else { 0 };
    let margin_hrs = hrs_left - exh_hrs;

    WindowRecord {
        r: "w".to_string(),
        ts: now,
        win: win.to_string(),
        pk,
        ceil,
        snap,
        reset,
        delta: 0.0,
        remain,
        hrs_left,
        fleet_pct_hr,
        exh_hrs,
        cutoff_risk,
        margin_hrs,
        bind: 0,
        safe_w: None,
    }
}

/// Find the binding (most constrained) window and set its `bind = 1`.
///
/// The binding window is the one with the smallest (most negative) `margin_hrs`.
/// All other windows get `bind = 0`. The binding window also gets `safe_w`
/// computed based on the provided per-worker rate.
pub fn find_binding_window(
    forecasts: &mut [WindowRecord],
    p75_rate_per_worker: f64,
) {
    if forecasts.is_empty() {
        return;
    }

    // Find the index of the window with the smallest margin_hrs
    let binding_idx = forecasts
        .iter()
        .enumerate()
        .min_by(|(_, a), (_, b)| {
            a.margin_hrs
                .partial_cmp(&b.margin_hrs)
                .unwrap_or(std::cmp::Ordering::Equal)
        })
        .map(|(i, _)| i)
        .unwrap_or(0);

    for (i, rec) in forecasts.iter_mut().enumerate() {
        if i == binding_idx {
            rec.bind = 1;
            rec.safe_w = Some(compute_safe_workers(
                rec.remain,
                rec.hrs_left,
                p75_rate_per_worker,
            ));
        } else {
            rec.bind = 0;
            rec.safe_w = None;
        }
    }
}

/// Compute the maximum number of workers where exhaustion time >= window time.
///
/// `safe_w = floor(remaining_pct / (p75_rate_per_worker * hrs_left))`
/// Returns `u32::MAX` when there's no constraint (zero rate or zero hours).
pub fn compute_safe_workers(remaining_pct: f64, hrs_left: f64, p75_rate_per_worker: f64) -> u32 {
    if p75_rate_per_worker <= 0.0 || hrs_left <= 0.0 {
        return u32::MAX;
    }

    let safe = (remaining_pct / (p75_rate_per_worker * hrs_left)).floor() as u64;
    safe.min(u32::MAX as u64) as u32
}

/// Generate WindowRecords for all three usage windows and find the binding one.
///
/// Produces exactly 3 records: five_hour, seven_day, seven_day_sonnet.
pub fn compute_window_forecasts(
    windows: &[(&str, f64, DateTime<Utc>)], // (name, snap, reset)
    ceil: f64,
    now: DateTime<Utc>,
    fleet_pct_hr: f64,
    pk: bool,
    p75_rate_per_worker: f64,
) -> Vec<WindowRecord> {
    let mut forecasts: Vec<WindowRecord> = windows
        .iter()
        .map(|(name, snap, reset)| {
            compute_window_forecast(name, *snap, ceil, *reset, now, fleet_pct_hr, pk)
        })
        .collect();

    find_binding_window(&mut forecasts, p75_rate_per_worker);
    forecasts
}

// ---------------------------------------------------------------------------
// JSONL record types: InstanceRecord (i), FleetRecord (f), and helpers
// ---------------------------------------------------------------------------

/// Returns `true` if `t` falls within peak hours: 8 AM–2 PM ET, weekdays only.
///
/// Peak window aligns with `promotions.json` (`peak_start_hour_et=8`, `peak_end_hour_et=14`).
pub fn is_peak(t: DateTime<Utc>) -> bool {
    let et = t.with_timezone(&Eastern);
    let weekday = et.weekday().num_days_from_monday(); // 0=Mon … 6=Sun
    let hour = et.hour();
    weekday < 5 && hour >= 8 && hour < 14
}

/// Returns the hour (0–23) in US Eastern time at timestamp `t`.
pub fn hr_et(t: DateTime<Utc>) -> u8 {
    t.with_timezone(&Eastern).hour() as u8
}

/// Returns the day-of-week in US Eastern time at timestamp `t` (0=Mon … 6=Sun).
pub fn dow(t: DateTime<Utc>) -> u8 {
    t.with_timezone(&Eastern)
        .weekday()
        .num_days_from_monday() as u8
}

/// Instance-level JSONL record — type `"i"`, one row per session per collection interval.
///
/// All token types appear as columns on the same row. Since each session runs
/// one model, columns are not model-prefixed; the `model` field carries the identity.
/// `p5h`, `p7d`, `p7ds` are `null` at write time; the governor annotates them later.
#[derive(Debug, Clone, Serialize)]
pub struct InstanceRecord {
    /// Record type discriminator (always `"i"`)
    #[serde(rename = "r")]
    pub r: String,

    /// Timestamp when this record was written
    #[serde(rename = "ts")]
    pub ts: DateTime<Utc>,

    /// Interval start time
    #[serde(rename = "t0")]
    pub t0: DateTime<Utc>,

    /// Interval end time
    #[serde(rename = "t1")]
    pub t1: DateTime<Utc>,

    /// Worker session name (e.g., tmux session name)
    #[serde(rename = "sess")]
    pub sess: String,

    /// Session ID (short hash / stem from the JSONL file path)
    #[serde(rename = "sid")]
    pub sid: String,

    /// Model identifier (e.g., `"claude-sonnet-4-20250514"`)
    #[serde(rename = "model")]
    pub model: String,

    /// Peak flag: 1 = peak hours (8–14 ET weekdays), 0 = off-peak
    #[serde(rename = "pk")]
    pub pk: u8,

    /// Hour of day in US Eastern time at `t0` (0–23)
    #[serde(rename = "hr_et")]
    pub hr_et: u8,

    /// Day of week in US Eastern time at `t0` (0=Mon … 6=Sun)
    #[serde(rename = "dow")]
    pub dow: u8,

    /// Input token count
    #[serde(rename = "input-n")]
    pub input_n: u64,

    /// Input token cost (USD)
    #[serde(rename = "input-usd")]
    pub input_usd: f64,

    /// Output token count
    #[serde(rename = "output-n")]
    pub output_n: u64,

    /// Output token cost (USD)
    #[serde(rename = "output-usd")]
    pub output_usd: f64,

    /// Cache read token count
    #[serde(rename = "r-cache-n")]
    pub r_cache_n: u64,

    /// Cache read cost (USD)
    #[serde(rename = "r-cache-usd")]
    pub r_cache_usd: f64,

    /// Cache write (5-minute TTL) token count
    #[serde(rename = "w-cache-n")]
    pub w_cache_n: u64,

    /// Cache write (5-minute TTL) cost (USD)
    #[serde(rename = "w-cache-usd")]
    pub w_cache_usd: f64,

    /// Cache write (1-hour TTL) token count — Bedrock only; near-zero on standard API
    #[serde(rename = "w-cache-1h-n")]
    pub w_cache_1h_n: u64,

    /// Cache write (1-hour TTL) cost (USD)
    #[serde(rename = "w-cache-1h-usd")]
    pub w_cache_1h_usd: f64,

    /// Total cost (USD) for this interval
    #[serde(rename = "total-usd")]
    pub total_usd: f64,

    /// Cache efficiency: cache_read_tokens / (input_tokens + cache_read_tokens)
    /// 0.0 when no input tokens were consumed this interval
    #[serde(rename = "cache-eff")]
    pub cache_eff: f64,

    /// 5-hour window utilization % delta — `null` until governor annotates
    #[serde(rename = "p5h", skip_serializing_if = "Option::is_none")]
    pub p5h: Option<f64>,

    /// 7-day window utilization % delta — `null` until governor annotates
    #[serde(rename = "p7d", skip_serializing_if = "Option::is_none")]
    pub p7d: Option<f64>,

    /// 7-day Sonnet window utilization % delta — `null` until governor annotates
    #[serde(rename = "p7ds", skip_serializing_if = "Option::is_none")]
    pub p7ds: Option<f64>,
}

impl InstanceRecord {
    /// Create a new InstanceRecord from a UsageRecord and DollarBreakdown.
    pub fn new(
        ts: DateTime<Utc>,
        t0: DateTime<Utc>,
        t1: DateTime<Utc>,
        session: String,
        sid: String,
        model: String,
        usage: &UsageRecord,
        dollars: &crate::pricing::DollarBreakdown,
    ) -> Self {
        let total_input = usage.input_tokens + usage.cache_read_tokens;
        let cache_eff = if total_input > 0 {
            usage.cache_read_tokens as f64 / total_input as f64
        } else {
            0.0
        };
        Self {
            r: "i".to_string(),
            ts,
            t0,
            t1,
            sess: session,
            sid,
            model,
            pk: if is_peak(t0) { 1 } else { 0 },
            hr_et: hr_et(t0),
            dow: dow(t0),
            input_n: usage.input_tokens,
            input_usd: dollars.input_usd,
            output_n: usage.output_tokens,
            output_usd: dollars.output_usd,
            r_cache_n: usage.cache_read_tokens,
            r_cache_usd: dollars.cache_read_usd,
            w_cache_n: usage.cache_write_5m_tokens,
            w_cache_usd: dollars.cache_write_5m_usd,
            w_cache_1h_n: usage.cache_write_1h_tokens,
            w_cache_1h_usd: dollars.cache_write_1h_usd,
            total_usd: dollars.total_usd,
            cache_eff,
            p5h: None,
            p7d: None,
            p7ds: None,
        }
    }
}

/// Summed token-type data for one model within a fleet record.
#[derive(Debug, Clone, Default)]
pub struct ModelTokens {
    pub input_n: u64,
    pub input_usd: f64,
    pub output_n: u64,
    pub output_usd: f64,
    pub r_cache_n: u64,
    pub r_cache_usd: f64,
    pub w_cache_n: u64,
    pub w_cache_usd: f64,
    pub w_cache_1h_n: u64,
    pub w_cache_1h_usd: f64,
}

/// Fleet-level JSONL record — type `"f"`, one row per collection interval.
///
/// Aggregates all worker instances. Per-model columns are dynamic (all configured
/// models appear, zero-filled when inactive). Use [`FleetRecord::to_json_value`] to
/// serialize to a flat JSON object.
#[derive(Debug, Clone)]
pub struct FleetRecord {
    /// Timestamp when this record was written
    pub ts: DateTime<Utc>,

    /// Interval start time
    pub t0: DateTime<Utc>,

    /// Interval end time
    pub t1: DateTime<Utc>,

    /// Peak flag: 1 = peak hours (8–14 ET weekdays), 0 = off-peak
    pub pk: u8,

    /// Hour of day in US Eastern time at `t0` (0–23)
    pub hr_et: u8,

    /// Day of week in US Eastern time at `t0` (0=Mon … 6=Sun)
    pub dow: u8,

    /// Number of active workers this interval
    pub workers: usize,

    /// Per-model token data in config order.
    /// Every configured model is present, zero-filled when inactive.
    pub model_data: Vec<(String, ModelTokens)>,

    /// Total fleet cost (USD) for this interval
    pub total_usd: f64,

    /// 75th-percentile per-worker USD/hr (nearest-rank method)
    pub p75_usd_hr: f64,

    /// Population standard deviation of per-worker USD/hr
    pub std_usd_hr: f64,

    /// 5-hour window utilization % delta — `null` until governor annotates
    pub p5h: Option<f64>,

    /// 7-day window utilization % delta — `null` until governor annotates
    pub p7d: Option<f64>,

    /// 7-day Sonnet window utilization % delta — `null` until governor annotates
    pub p7ds: Option<f64>,

    /// USD cost per 1 % of the Sonnet 7-day window — promotion-validation signal.
    /// `null` when `p7ds` is null.
    pub usd_per_pct_7ds: Option<f64>,

    /// Fleet-level cache efficiency: weighted average by total input tokens across all instances.
    /// 0.0 when no input tokens were consumed this interval.
    pub fleet_cache_eff: f64,

    /// 25th percentile of per-instance cache efficiency values (nearest-rank method).
    /// 0.0 when no instances reported this interval.
    pub cache_eff_p25: f64,
}

/// Token-type suffixes used in fleet record column names, in schema order.
const TOK_SUFFIXES: &[(&str, bool)] = &[
    ("input-n", false),
    ("input-usd", true),
    ("output-n", false),
    ("output-usd", true),
    ("r-cache-n", false),
    ("r-cache-usd", true),
    ("w-cache-n", false),
    ("w-cache-usd", true),
    ("w-cache-1h-n", false),
    ("w-cache-1h-usd", true),
];

impl FleetRecord {
    /// Serialize to a flat `serde_json::Value` object with all per-model columns.
    pub fn to_json_value(&self) -> serde_json::Value {
        use serde_json::{Map, Number, Value};

        let mut map = Map::new();

        // Fixed header fields
        map.insert("r".into(), Value::String("f".into()));
        map.insert("ts".into(), Value::String(self.ts.to_rfc3339()));
        map.insert("t0".into(), Value::String(self.t0.to_rfc3339()));
        map.insert("t1".into(), Value::String(self.t1.to_rfc3339()));
        map.insert("pk".into(), Value::Number(self.pk.into()));
        map.insert("hr_et".into(), Value::Number(self.hr_et.into()));
        map.insert("dow".into(), Value::Number(self.dow.into()));
        map.insert("workers".into(), Value::Number(self.workers.into()));

        // Per-model columns
        for (model, tok) in &self.model_data {
            let raw: [f64; 10] = [
                tok.input_n as f64,
                tok.input_usd,
                tok.output_n as f64,
                tok.output_usd,
                tok.r_cache_n as f64,
                tok.r_cache_usd,
                tok.w_cache_n as f64,
                tok.w_cache_usd,
                tok.w_cache_1h_n as f64,
                tok.w_cache_1h_usd,
            ];
            for (i, (suffix, is_float)) in TOK_SUFFIXES.iter().enumerate() {
                let key = format!("{}-{}", model, suffix);
                let val = if *is_float {
                    Number::from_f64(raw[i])
                        .map(Value::Number)
                        .unwrap_or(Value::Number(0.into()))
                } else {
                    Value::Number((raw[i] as u64).into())
                };
                map.insert(key, val);
            }
        }

        // Fleet totals
        let insert_f64 = |m: &mut Map<String, Value>, k: &str, v: f64| {
            m.insert(
                k.into(),
                Number::from_f64(v)
                    .map(Value::Number)
                    .unwrap_or(Value::Number(0.into())),
            );
        };
        insert_f64(&mut map, "total-usd", self.total_usd);
        insert_f64(&mut map, "p75-usd-hr", self.p75_usd_hr);
        insert_f64(&mut map, "std-usd-hr", self.std_usd_hr);
        insert_f64(&mut map, "fleet-cache-eff", self.fleet_cache_eff);
        insert_f64(&mut map, "cache-eff-p25", self.cache_eff_p25);

        // Window snapshots (null until annotated)
        let opt_val = |v: Option<f64>| {
            v.and_then(Number::from_f64)
                .map(Value::Number)
                .unwrap_or(Value::Null)
        };
        map.insert("p5h".into(), opt_val(self.p5h));
        map.insert("p7d".into(), opt_val(self.p7d));
        map.insert("p7ds".into(), opt_val(self.p7ds));
        map.insert("usd-per-pct-7ds".into(), opt_val(self.usd_per_pct_7ds));

        Value::Object(map)
    }
}

/// Aggregate a slice of instance records into a single fleet record.
///
/// * Sums token counts and costs per model across all instances.
/// * Zero-fills models from `all_models` that had no activity.
/// * Computes `p75_usd_hr` (nearest-rank) and `std_usd_hr` (population) over
///   per-worker USD/hr values derived from the interval duration `t1 − t0`.
/// * Window snapshot fields are left `None` — the governor annotates them later.
pub fn aggregate_to_fleet(
    instances: &[InstanceRecord],
    ts: DateTime<Utc>,
    t0: DateTime<Utc>,
    t1: DateTime<Utc>,
    all_models: &[String],
) -> FleetRecord {
    // Initialise per-model accumulators to zero for every configured model
    let mut model_map: HashMap<String, ModelTokens> = all_models
        .iter()
        .map(|m| (m.clone(), ModelTokens::default()))
        .collect();

    // Sum token data from all instances
    for inst in instances {
        let entry = model_map.entry(inst.model.clone()).or_default();
        entry.input_n += inst.input_n;
        entry.input_usd += inst.input_usd;
        entry.output_n += inst.output_n;
        entry.output_usd += inst.output_usd;
        entry.r_cache_n += inst.r_cache_n;
        entry.r_cache_usd += inst.r_cache_usd;
        entry.w_cache_n += inst.w_cache_n;
        entry.w_cache_usd += inst.w_cache_usd;
        entry.w_cache_1h_n += inst.w_cache_1h_n;
        entry.w_cache_1h_usd += inst.w_cache_1h_usd;
    }

    let total_usd: f64 = instances.iter().map(|i| i.total_usd).sum();

    // Per-worker variance stats
    let elapsed_hours = (t1 - t0).num_seconds() as f64 / 3600.0;
    let (p75_usd_hr, std_usd_hr) = if instances.is_empty() || elapsed_hours <= 0.0 {
        (0.0, 0.0)
    } else {
        let mut rates: Vec<f64> = instances
            .iter()
            .map(|i| i.total_usd / elapsed_hours)
            .collect();

        let n = rates.len();
        rates.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));

        // Nearest-rank p75: index = ceil(n * 0.75) - 1, clamped to [0, n-1]
        let p75_idx = ((n as f64 * 0.75).ceil() as usize)
            .saturating_sub(1)
            .min(n - 1);
        let p75 = rates[p75_idx];

        // Population standard deviation
        let mean = rates.iter().sum::<f64>() / n as f64;
        let variance = rates.iter().map(|v| (v - mean).powi(2)).sum::<f64>() / n as f64;
        let std = variance.sqrt();

        (p75, std)
    };

    // Build ordered model_data list preserving config order; include any
    // extra models from instances that weren't in all_models at the end.
    let mut model_data: Vec<(String, ModelTokens)> = all_models
        .iter()
        .map(|m| (m.clone(), model_map.remove(m).unwrap_or_default()))
        .collect();
    // Append any instance models not in all_models (e.g., unknown model)
    for (m, tok) in model_map {
        model_data.push((m, tok));
    }

    // Per-instance cache efficiency values
    let cache_eff_values: Vec<f64> = instances
        .iter()
        .map(|i| {
            let total_input = i.input_n + i.r_cache_n;
            if total_input > 0 {
                i.r_cache_n as f64 / total_input as f64
            } else {
                0.0
            }
        })
        .collect();

    // Fleet cache efficiency: weighted average by (input_n + r_cache_n)
    let total_input_sum: u64 = instances.iter().map(|i| i.input_n + i.r_cache_n).sum();
    let fleet_cache_eff = if total_input_sum > 0 {
        let weighted_cache_reads: u64 = instances.iter().map(|i| i.r_cache_n).sum();
        weighted_cache_reads as f64 / total_input_sum as f64
    } else {
        0.0
    };

    // 25th percentile cache efficiency (nearest-rank method)
    let cache_eff_p25 = if cache_eff_values.is_empty() {
        0.0
    } else {
        let mut sorted = cache_eff_values.clone();
        sorted.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
        let n = sorted.len();
        let p25_idx = ((n as f64 * 0.25).ceil() as usize)
            .saturating_sub(1)
            .min(n - 1);
        sorted[p25_idx]
    };

    let pk = if is_peak(t0) { 1 } else { 0 };

    FleetRecord {
        ts,
        t0,
        t1,
        pk,
        hr_et: hr_et(t0),
        dow: dow(t0),
        workers: instances.len(),
        model_data,
        total_usd,
        p75_usd_hr,
        std_usd_hr,
        p5h: None,
        p7d: None,
        p7ds: None,
        usd_per_pct_7ds: None,
        fleet_cache_eff,
        cache_eff_p25,
    }
}

// ---------------------------------------------------------------------------
// Collection pass orchestration
// ---------------------------------------------------------------------------

/// Default path for token-history.jsonl
pub fn default_history_path() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".needle")
        .join("state")
        .join("token-history.jsonl")
}

/// Default path for token-history.db
pub fn default_db_path() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".needle")
        .join("state")
        .join("token-history.db")
}

/// Default path for collector-cursors.json
pub fn default_cursor_path() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".needle")
        .join("state")
        .join("collector-cursors.json")
}

/// Default base path for Claude Code session JSONL files
pub fn default_session_base() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".claude")
        .join("projects")
}

/// Result of a single collection pass.
pub struct CollectionResult {
    /// Number of new lines processed
    pub lines_processed: usize,
    /// Number of instance records written
    pub instance_records: usize,
    /// Number of fleet records written
    pub fleet_records: usize,
    /// Number of window records written
    pub window_records: usize,
    /// Total USD across all instances
    pub total_usd: f64,
}

/// Run a single collection pass.
///
/// 1. Discovers JSONL files under the session base directory
/// 2. Reads new lines using cursor tracking
/// 3. Parses usage blocks and accumulates per-session deltas
/// 4. Computes dollar costs using the pricing engine
/// 5. Writes instance (i), fleet (f), and window (w) records to JSONL
/// 6. Mirrors to SQLite
/// 7. Saves cursor state
pub fn run_collection_pass() -> anyhow::Result<CollectionResult> {
    use crate::pricing::PricingEngine;

    let history_path = default_history_path();
    let db_path = default_db_path();
    let cursor_path = default_cursor_path();
    let session_base = default_session_base();

    let pricing_engine = PricingEngine::new()?;
    let config = pricing_engine.config();

    // Collect all configured model names
    let all_models: Vec<String> = config.pricing.models.keys().cloned().collect();

    // Load cursors
    let mut cursors = CursorStore::load(&cursor_path)
        .map_err(|e| anyhow::anyhow!("Failed to load cursors: {}", e))?;

    // Discover JSONL files
    let files = discover_jsonl_files(&session_base);
    if files.is_empty() {
        log::info!("[collector] no JSONL files found under {}", session_base.display());
        return Ok(CollectionResult {
            lines_processed: 0,
            instance_records: 0,
            fleet_records: 0,
            window_records: 0,
            total_usd: 0.0,
        });
    }

    let now = chrono::Utc::now();
    let t0 = now - chrono::Duration::minutes(5); // Assume 5-minute intervals
    let t1 = now;

    // Accumulate per-session per-model usage
    let mut session_usage: HashMap<(String, String), UsageRecord> = HashMap::new();
    let mut total_lines = 0usize;

    for file_path in &files {
        let lines = read_new_lines(file_path, &mut cursors)
            .map_err(|e| anyhow::anyhow!("Failed to read {}: {}", file_path.display(), e))?;

        for line in &lines {
            total_lines += 1;
            if let Ok(jsonl_line) = serde_json::from_str::<JsonlLine>(line) {
                if let Some(usage) = parse_usage_block(&jsonl_line, file_path) {
                    if !usage.is_zero() {
                        let key = (usage.session.clone(), usage.model.clone());
                        let entry = session_usage.entry(key).or_insert_with(|| {
                            UsageRecord::zero(usage.model.clone(), usage.session.clone())
                        });
                        entry.input_tokens += usage.input_tokens;
                        entry.output_tokens += usage.output_tokens;
                        entry.cache_read_tokens += usage.cache_read_tokens;
                        entry.cache_write_5m_tokens += usage.cache_write_5m_tokens;
                        entry.cache_write_1h_tokens += usage.cache_write_1h_tokens;
                    }
                }
            }
        }
    }

    if session_usage.is_empty() {
        log::info!("[collector] no new usage data found");
        // Still save cursors even if no data
        cursors.save(&cursor_path)
            .map_err(|e| anyhow::anyhow!("Failed to save cursors: {}", e))?;
        return Ok(CollectionResult {
            lines_processed: total_lines,
            instance_records: 0,
            fleet_records: 0,
            window_records: 0,
            total_usd: 0.0,
        });
    }

    // Build instance records
    let mut instances: Vec<InstanceRecord> = Vec::new();
    let mut jsonl_records: Vec<serde_json::Value> = Vec::new();
    let mut total_usd = 0.0;

    for ((session, model), usage) in &session_usage {
        let dollars = pricing_engine.compute_dollars(usage);
        total_usd += dollars.total_usd;

        let rec = InstanceRecord::new(
            now,
            t0,
            t1,
            session.clone(),
            crate::collector::extract_session_id(Path::new("")),
            model.clone(),
            usage,
            &dollars,
        );

        let json = serde_json::to_value(&rec)?;
        jsonl_records.push(json);
        instances.push(rec);
    }

    // Build fleet record
    let fleet = aggregate_to_fleet(&instances, now, t0, t1, &all_models);
    let fleet_json = fleet.to_json_value();
    jsonl_records.push(fleet_json);

    // Write to JSONL
    append_jsonl(&history_path, &jsonl_records)
        .map_err(|e| anyhow::anyhow!("Failed to write JSONL: {}", e))?;

    // Mirror to SQLite
    match crate::db::open_db(&db_path) {
        Ok(conn) => {
            if let Err(e) = crate::db::create_schema(&conn) {
                log::warn!("[collector] failed to create SQLite schema: {}", e);
            } else {
                for record in &jsonl_records {
                    if let Err(e) = crate::db::insert_record(&conn, record) {
                        log::warn!("[collector] failed to insert record: {}", e);
                    }
                }
            }
        }
        Err(e) => {
            log::warn!("[collector] failed to open SQLite: {}", e);
        }
    }

    // Save cursors
    cursors.save(&cursor_path)
        .map_err(|e| anyhow::anyhow!("Failed to save cursors: {}", e))?;

    let result = CollectionResult {
        lines_processed: total_lines,
        instance_records: instances.len(),
        fleet_records: 1,
        window_records: 0,
        total_usd,
    };

    log::info!(
        "[collector] pass complete: {} lines, {} instances, ${:.4} total",
        result.lines_processed,
        result.instance_records,
        result.total_usd,
    );

    Ok(result)
}

/// Run the collector in daemon mode (continuous loop).
///
/// Runs `run_collection_pass()` every `interval_secs` seconds.
/// Handles SIGINT/SIGTERM for graceful shutdown.
pub fn run_daemon(interval_secs: u64) -> anyhow::Result<()> {
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::Arc;
    use std::thread;
    use std::time::Duration;

    let running = Arc::new(AtomicBool::new(true));
    let r = running.clone();

    // SIGTERM handler
    ctrlc_handler(r)?;

    log::info!(
        "[collector] daemon started (interval: {}s, pid: {})",
        interval_secs,
        std::process::id()
    );

    while running.load(Ordering::Relaxed) {
        let start = std::time::Instant::now();

        if let Err(e) = run_collection_pass() {
            log::error!("[collector] collection pass failed: {}", e);
        }

        let elapsed = start.elapsed();
        let sleep_time = Duration::from_secs(interval_secs).saturating_sub(elapsed);

        // Sleep in small increments to check for shutdown
        let check_interval = Duration::from_secs(1);
        let mut remaining = sleep_time;
        while remaining > Duration::ZERO && running.load(Ordering::Relaxed) {
            let sleep = std::cmp::min(remaining, check_interval);
            thread::sleep(sleep);
            remaining = remaining.saturating_sub(sleep);
        }
    }

    log::info!("[collector] daemon shutting down");
    Ok(())
}

/// Install a SIGINT/SIGTERM handler that sets the flag to false.
fn ctrlc_handler(running: Arc<std::sync::atomic::AtomicBool>) -> anyhow::Result<()> {
    ctrlc::set_handler(move || {
        log::info!("[collector] received shutdown signal");
        running.store(false, std::sync::atomic::Ordering::Relaxed);
    })
    .map_err(|e| anyhow::anyhow!("Failed to install signal handler: {}", e))
}

/// Append JSON records to a JSONL file, one object per line.
///
/// Creates the file (and parent directories) if they don't exist.
/// All records are serialised into a single buffer and written with one
/// `write_all` call to prevent partial-line writes.
pub fn append_jsonl(path: &Path, records: &[serde_json::Value]) -> Result<()> {
    if records.is_empty() {
        return Ok(());
    }

    // Ensure parent directory exists
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)?;
        }
    }

    // Build complete content first — prevents partial-line writes on failure
    let mut buf = String::new();
    for record in records {
        buf.push_str(&serde_json::to_string(record)?);
        buf.push('\n');
    }

    let mut file = OpenOptions::new().create(true).append(true).open(path)?;
    file.write_all(buf.as_bytes())?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn test_usage_record_zero() {
        let record = UsageRecord::zero("test-model".to_string(), "test-session".to_string());
        assert_eq!(record.total_tokens(), 0);
        assert!(record.is_zero());
    }

    #[test]
    fn test_usage_record_total() {
        let record = UsageRecord {
            input_tokens: 1000,
            output_tokens: 500,
            cache_read_tokens: 200,
            cache_write_5m_tokens: 100,
            cache_write_1h_tokens: 50,
            model: "test".to_string(),
            session: "session".to_string(),
        };
        assert_eq!(record.total_tokens(), 1850);
        assert!(!record.is_zero());
    }

    #[test]
    fn test_parse_jsonl_usage() {
        let json = r#"{"type":"message","message":{"role":"assistant","content":[],"model":"claude-sonnet-4-20250514","usage":{"input_tokens":1000,"output_tokens":500,"cache_creation_input_tokens":100,"cache_read_input_tokens":50,"cache_creation":{"ephemeral_5m_input_tokens":50,"ephemeral_1h_input_tokens":50}}}}"#;

        let line: JsonlLine = serde_json::from_str(json).unwrap();
        assert_eq!(line.msg_type, Some("message".to_string()));

        let msg = line.message.unwrap();
        assert_eq!(msg.model, Some("claude-sonnet-4-20250514".to_string()));

        let usage = msg.usage.unwrap();
        assert_eq!(usage.input_tokens, 1000);
        assert_eq!(usage.output_tokens, 500);
        assert_eq!(usage.cache_creation_input_tokens, Some(100));
        assert_eq!(usage.cache_read_input_tokens, Some(50));

        let cache_creation = usage.cache_creation.unwrap();
        assert_eq!(cache_creation.ephemeral_5m_input_tokens, Some(50));
        assert_eq!(cache_creation.ephemeral_1h_input_tokens, Some(50));
    }

    // Cursor tests

    #[test]
    fn cursor_round_trip() {
        let temp_dir = TempDir::new().unwrap();
        let cursor_path = temp_dir.path().join("cursors.json");

        // Create and populate cursor store
        let mut store = CursorStore::default();
        store.set_offset(PathBuf::from("/path/to/file1.jsonl"), 1000);
        store.set_offset(PathBuf::from("/path/to/file2.jsonl"), 2500);
        store.set_offset(PathBuf::from("/path/to/nested/file3.jsonl"), 500);

        // Save
        store.save(&cursor_path).unwrap();

        // Verify no .tmp file remains
        assert!(!cursor_path.with_extension("tmp").exists());

        // Load back
        let loaded = CursorStore::load(&cursor_path).unwrap();

        // Verify all offsets match
        assert_eq!(loaded.get_offset(Path::new("/path/to/file1.jsonl")), 1000);
        assert_eq!(loaded.get_offset(Path::new("/path/to/file2.jsonl")), 2500);
        assert_eq!(
            loaded.get_offset(Path::new("/path/to/nested/file3.jsonl")),
            500
        );
    }

    #[test]
    fn cursor_load_nonexistent_returns_empty() {
        let temp_dir = TempDir::new().unwrap();
        let cursor_path = temp_dir.path().join("nonexistent.json");

        // Should not error, return empty store
        let store = CursorStore::load(&cursor_path).unwrap();

        // Any file should return offset 0
        assert_eq!(store.get_offset(Path::new("/any/file.jsonl")), 0);
    }

    #[test]
    fn cursor_get_offset_unknown_returns_zero() {
        let mut store = CursorStore::default();
        store.set_offset(PathBuf::from("/known/file.jsonl"), 100);

        // Unknown file returns 0
        assert_eq!(store.get_offset(Path::new("/unknown/file.jsonl")), 0);

        // Known file returns stored offset
        assert_eq!(store.get_offset(Path::new("/known/file.jsonl")), 100);
    }

    #[test]
    fn discover_jsonl_finds_nested_files() {
        let temp_dir = TempDir::new().unwrap();

        // Create nested directory structure with JSONL files
        let nested = temp_dir.path().join("subdir").join("nested");
        fs::create_dir_all(&nested).unwrap();

        fs::File::create(temp_dir.path().join("root.jsonl")).unwrap();
        fs::File::create(temp_dir.path().join("subdir").join("level1.jsonl")).unwrap();
        fs::File::create(nested.join("level2.jsonl")).unwrap();

        let files = discover_jsonl_files(temp_dir.path());

        // Should find all 3 JSONL files
        assert_eq!(files.len(), 3);

        // Should be sorted by full path
        let sorted = files.windows(2).all(|w| w[0] <= w[1]);
        assert!(sorted, "Files should be sorted by path");

        // Verify all expected files are present
        let names: Vec<String> = files
            .iter()
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        assert!(names.contains(&"root.jsonl".to_string()));
        assert!(names.contains(&"level1.jsonl".to_string()));
        assert!(names.contains(&"level2.jsonl".to_string()));
    }

    #[test]
    fn discover_jsonl_ignores_non_jsonl() {
        let temp_dir = TempDir::new().unwrap();

        // Create various file types
        fs::File::create(temp_dir.path().join("data.jsonl")).unwrap();
        fs::File::create(temp_dir.path().join("config.json")).unwrap();
        fs::File::create(temp_dir.path().join("readme.md")).unwrap();
        fs::File::create(temp_dir.path().join("script.sh")).unwrap();

        let files = discover_jsonl_files(temp_dir.path());

        // Should only find the .jsonl file
        assert_eq!(files.len(), 1);
        assert_eq!(
            files[0].file_name().unwrap().to_string_lossy(),
            "data.jsonl"
        );
    }

    #[test]
    fn discover_jsonl_empty_directory() {
        let temp_dir = TempDir::new().unwrap();

        let files = discover_jsonl_files(temp_dir.path());

        assert!(files.is_empty());
    }

    mod model {
        use super::*;

        #[test]
        fn extract_model_returns_model_field() {
            let json = serde_json::json!({"model": "claude-sonnet-4-20250514"});
            assert_eq!(extract_model(json), "claude-sonnet-4-20250514");
        }

        #[test]
        fn extract_model_returns_unknown_when_missing() {
            let json = serde_json::json!({"other_field": "value"});
            assert_eq!(extract_model(json), "unknown");
        }

        #[test]
        fn extract_model_returns_unknown_when_null() {
            let json = serde_json::json!({"model": null});
            assert_eq!(extract_model(json), "unknown");
        }

        #[test]
        fn extract_session_id_returns_stem() {
            let path = Path::new("/home/user/.claude/projects/foo/abc123.jsonl");
            assert_eq!(extract_session_id(path), "abc123");
        }

        #[test]
        fn extract_session_id_handles_nested_path() {
            let path = Path::new("/deeply/nested/path/session-xyz-789.jsonl");
            assert_eq!(extract_session_id(path), "session-xyz-789");
        }

        #[test]
        fn extract_session_id_returns_unknown_for_no_stem() {
            // Path with no filename component
            let path = Path::new("/");
            assert_eq!(extract_session_id(path), "unknown");
        }

        #[test]
        fn infer_model_from_path_returns_none_for_generic() {
            let path = Path::new("/home/user/.claude/projects/foo/session.jsonl");
            assert!(infer_model_from_path(path).is_none());
        }

        #[test]
        fn infer_model_from_path_detects_sonnet() {
            let path = Path::new("/home/user/sessions/sonnet/test.jsonl");
            assert_eq!(infer_model_from_path(path), Some("claude-sonnet".to_string()));
        }

        #[test]
        fn infer_model_from_path_detects_opus() {
            let path = Path::new("/home/user/opus-sessions/test.jsonl");
            assert_eq!(infer_model_from_path(path), Some("claude-opus".to_string()));
        }

        #[test]
        fn infer_model_from_path_detects_haiku() {
            let path = Path::new("/home/user/haiku/test.jsonl");
            assert_eq!(infer_model_from_path(path), Some("claude-haiku".to_string()));
        }

        #[test]
        fn infer_model_from_path_is_case_insensitive() {
            let path = Path::new("/home/user/SONNET/test.jsonl");
            assert_eq!(infer_model_from_path(path), Some("claude-sonnet".to_string()));
        }

        #[test]
        fn parse_usage_block_extracts_all_fields() {
            let json = r#"{"type":"message","message":{"role":"assistant","content":[],"model":"claude-sonnet-4-20250514","usage":{"input_tokens":1000,"output_tokens":500,"cache_creation_input_tokens":100,"cache_read_input_tokens":50,"cache_creation":{"ephemeral_5m_input_tokens":60,"ephemeral_1h_input_tokens":40}}}}"#;
            let line: JsonlLine = serde_json::from_str(json).unwrap();
            let path = Path::new("/sessions/test-session.jsonl");

            let record = parse_usage_block(&line, path).unwrap();

            assert_eq!(record.input_tokens, 1000);
            assert_eq!(record.output_tokens, 500);
            assert_eq!(record.cache_read_tokens, 50);
            assert_eq!(record.cache_write_5m_tokens, 60);
            assert_eq!(record.cache_write_1h_tokens, 40);
            assert_eq!(record.model, "claude-sonnet-4-20250514");
            assert_eq!(record.session, "test-session");
        }

        #[test]
        fn parse_usage_block_uses_path_inference_when_no_model() {
            let json = r#"{"type":"message","message":{"role":"assistant","content":[],"usage":{"input_tokens":100,"output_tokens":50}}}"#;
            let line: JsonlLine = serde_json::from_str(json).unwrap();
            let path = Path::new("/sessions/sonnet/test.jsonl");

            let record = parse_usage_block(&line, path).unwrap();

            assert_eq!(record.model, "claude-sonnet");
        }

        #[test]
        fn parse_usage_block_returns_unknown_when_no_model_hints() {
            let json = r#"{"type":"message","message":{"role":"assistant","content":[],"usage":{"input_tokens":100,"output_tokens":50}}}"#;
            let line: JsonlLine = serde_json::from_str(json).unwrap();
            let path = Path::new("/sessions/test.jsonl");

            let record = parse_usage_block(&line, path).unwrap();

            assert_eq!(record.model, "unknown");
        }

        #[test]
        fn parse_usage_block_returns_none_for_non_message() {
            let json = r#"{"type":"other"}"#;
            let line: JsonlLine = serde_json::from_str(json).unwrap();
            let path = Path::new("/sessions/test.jsonl");

            assert!(parse_usage_block(&line, path).is_none());
        }

        #[test]
        fn multi_model_session_produces_different_records() {
            let path = Path::new("/sessions/multi-session.jsonl");

            // First line with Sonnet
            let json1 = r#"{"type":"message","message":{"role":"assistant","content":[],"model":"claude-sonnet-4-20250514","usage":{"input_tokens":1000,"output_tokens":500}}}"#;
            let line1: JsonlLine = serde_json::from_str(json1).unwrap();
            let record1 = parse_usage_block(&line1, path).unwrap();

            // Second line with Opus
            let json2 = r#"{"type":"message","message":{"role":"assistant","content":[],"model":"claude-opus-4-20250514","usage":{"input_tokens":2000,"output_tokens":800}}}"#;
            let line2: JsonlLine = serde_json::from_str(json2).unwrap();
            let record2 = parse_usage_block(&line2, path).unwrap();

            // Same session, different models
            assert_eq!(record1.session, "multi-session");
            assert_eq!(record2.session, "multi-session");
            assert_eq!(record1.model, "claude-sonnet-4-20250514");
            assert_eq!(record2.model, "claude-opus-4-20250514");
            assert_ne!(record1.model, record2.model);
        }
    }

    mod read_new {
        use super::*;
        use std::io::Write;
        use std::sync::{Mutex, OnceLock};

        // --- test logger for capturing log::warn! output ---

        static TEST_LOGS: OnceLock<Mutex<Vec<String>>> = OnceLock::new();

        struct TestLogger;

        impl log::Log for TestLogger {
            fn enabled(&self, _: &log::Metadata) -> bool {
                true
            }
            fn log(&self, record: &log::Record) {
                let logs = TEST_LOGS.get_or_init(|| Mutex::new(Vec::new()));
                logs.lock().unwrap().push(format!("{}", record.args()));
            }
            fn flush(&self) {}
        }

        static TEST_LOGGER: TestLogger = TestLogger;

        fn init_logger() {
            static ONCE: std::sync::Once = std::sync::Once::new();
            ONCE.call_once(|| {
                log::set_logger(&TEST_LOGGER).ok();
                log::set_max_level(log::LevelFilter::Warn);
            });
        }

        fn logs_containing(pattern: &str) -> Vec<String> {
            TEST_LOGS
                .get_or_init(|| Mutex::new(Vec::new()))
                .lock()
                .unwrap()
                .iter()
                .filter(|msg| msg.contains(pattern))
                .cloned()
                .collect()
        }

        #[test]
        fn initial_read_returns_all_lines() {
            let temp_dir = TempDir::new().unwrap();
            let file_path = temp_dir.path().join("test.jsonl");

            fs::write(&file_path, "line1\nline2\nline3\n").unwrap();

            let mut cursor = CursorStore::default();
            let lines = read_new_lines(&file_path, &mut cursor).unwrap();

            assert_eq!(lines, vec!["line1", "line2", "line3"]);
        }

        #[test]
        fn incremental_read_cursor_advances() {
            let temp_dir = TempDir::new().unwrap();
            let file_path = temp_dir.path().join("test.jsonl");

            fs::write(&file_path, "line1\nline2\n").unwrap();

            let mut cursor = CursorStore::default();
            let lines = read_new_lines(&file_path, &mut cursor).unwrap();
            assert_eq!(lines, vec!["line1", "line2"]);

            let offset_after_first = cursor.get_offset(&file_path);
            assert!(offset_after_first > 0);

            // Append 2 more lines
            let mut file = fs::OpenOptions::new()
                .append(true)
                .open(&file_path)
                .unwrap();
            file.write_all(b"line3\nline4\n").unwrap();
            drop(file);

            let lines2 = read_new_lines(&file_path, &mut cursor).unwrap();
            assert_eq!(lines2, vec!["line3", "line4"]);

            let offset_after_second = cursor.get_offset(&file_path);
            assert!(offset_after_second > offset_after_first);
        }

        #[test]
        fn shrinkage_guard_resets_cursor_and_logs() {
            init_logger();
            let temp_dir = TempDir::new().unwrap();
            let file_path = temp_dir.path().join("shrink.jsonl");

            // Write 100 bytes and set cursor to 100
            fs::write(&file_path, "a".repeat(100)).unwrap();
            let mut cursor = CursorStore::default();
            cursor.set_offset(file_path.clone(), 100);

            // Truncate to 10 bytes
            fs::write(&file_path, "bbbbbbbbbb").unwrap();

            let lines = read_new_lines(&file_path, &mut cursor).unwrap();

            // All 10 bytes returned as one line (no newlines)
            assert_eq!(lines, vec!["bbbbbbbbbb"]);

            // Cursor reset to new file size
            assert_eq!(cursor.get_offset(&file_path), 10);

            // Warning logged with the shrinkage details
            let path_str = file_path.to_string_lossy().to_string();
            let warnings = logs_containing(&path_str);
            assert!(
                !warnings.is_empty(),
                "Expected shrinkage warning to be logged"
            );
            let warning = &warnings[0];
            assert!(
                warning.contains("file shrunk"),
                "Warning should mention 'file shrunk', got: {warning}"
            );
            assert!(
                warning.contains("100") && warning.contains("10"),
                "Warning should contain old (100) and new (10) sizes, got: {warning}"
            );
        }

        #[test]
        fn empty_file_returns_empty_vec() {
            let temp_dir = TempDir::new().unwrap();
            let file_path = temp_dir.path().join("empty.jsonl");
            fs::write(&file_path, "").unwrap();

            let mut cursor = CursorStore::default();
            let lines = read_new_lines(&file_path, &mut cursor).unwrap();

            assert!(lines.is_empty());
            assert_eq!(cursor.get_offset(&file_path), 0);
        }

        #[test]
        fn trailing_newline_no_empty_line() {
            let temp_dir = TempDir::new().unwrap();
            let file_path = temp_dir.path().join("test.jsonl");
            fs::write(&file_path, "line1\nline2\nline3\n").unwrap();

            let mut cursor = CursorStore::default();
            let lines = read_new_lines(&file_path, &mut cursor).unwrap();

            assert_eq!(lines.len(), 3);
            assert_eq!(lines, vec!["line1", "line2", "line3"]);
        }
    }

    mod window_forecast {
        use super::*;
        use chrono::{Duration, Utc};

        fn base_now() -> DateTime<Utc> {
            "2026-03-20T10:00:00Z".parse().unwrap()
        }

        fn reset_5h_from(now: DateTime<Utc>) -> DateTime<Utc> {
            now + Duration::hours(3)
        }

        #[test]
        fn remain_is_ceil_minus_snap() {
            // ceil=90, snap=36 -> remain=54 (NOT 64)
            let now = base_now();
            let reset = reset_5h_from(now);
            let rec = compute_window_forecast("five_hour", 36.0, 90.0, reset, now, 2.0, false);

            assert_eq!(rec.remain, 54.0);
            assert_eq!(rec.ceil, 90.0);
            assert_eq!(rec.snap, 36.0);
        }

        #[test]
        fn hrs_left_computed_from_reset_minus_now() {
            let now = base_now();
            let reset = now + Duration::hours(3) + Duration::minutes(30);
            let rec = compute_window_forecast("five_hour", 50.0, 90.0, reset, now, 2.0, false);

            // 3.5 hours
            let expected = 3.5;
            assert!(
                (rec.hrs_left - expected).abs() < 1e-9,
                "expected hrs_left={}, got {}",
                expected,
                rec.hrs_left
            );
        }

        #[test]
        fn exh_hrs_is_remain_divided_by_fleet_pct_hr() {
            let now = base_now();
            let reset = reset_5h_from(now);
            // remain = 90 - 36 = 54, fleet_pct_hr = 2.0
            let rec = compute_window_forecast("five_hour", 36.0, 90.0, reset, now, 2.0, false);

            assert_eq!(rec.exh_hrs, 27.0); // 54 / 2
        }

        #[test]
        fn cutoff_risk_1_when_exh_less_than_hrs_left() {
            let now = base_now();
            let reset = now + Duration::hours(3);
            // remain=54, fleet_pct_hr=30 -> exh_hrs=1.8 < 3.0
            let rec = compute_window_forecast("five_hour", 36.0, 90.0, reset, now, 30.0, false);

            assert_eq!(rec.cutoff_risk, 1);
        }

        #[test]
        fn cutoff_risk_0_when_exh_greater_than_hrs_left() {
            let now = base_now();
            let reset = now + Duration::hours(3);
            // remain=54, fleet_pct_hr=2.0 -> exh_hrs=27 > 3.0
            let rec = compute_window_forecast("five_hour", 36.0, 90.0, reset, now, 2.0, false);

            assert_eq!(rec.cutoff_risk, 0);
        }

        #[test]
        fn margin_hrs_can_be_negative() {
            let now = base_now();
            let reset = now + Duration::hours(3);
            // remain=54, fleet_pct_hr=30 -> exh_hrs=1.8, margin=3.0-1.8=1.2
            let rec = compute_window_forecast("five_hour", 36.0, 90.0, reset, now, 30.0, false);

            assert!(
                (rec.margin_hrs - 1.2).abs() < 1e-9,
                "expected margin_hrs=1.2, got {}",
                rec.margin_hrs
            );

            // Now with a burn rate that makes exh_hrs > hrs_left -> negative margin
            let rec2 =
                compute_window_forecast("five_hour", 36.0, 90.0, reset, now, 2.0, false);
            // exh_hrs=27, margin=3-27=-24
            assert!(
                (rec2.margin_hrs - (-24.0)).abs() < 1e-9,
                "expected margin_hrs=-24.0, got {}",
                rec2.margin_hrs
            );
        }

        #[test]
        fn zero_fleet_pct_hr_gives_infinity_exh() {
            let now = base_now();
            let reset = reset_5h_from(now);
            let rec = compute_window_forecast("five_hour", 50.0, 90.0, reset, now, 0.0, false);

            assert!(rec.exh_hrs.is_infinite());
            assert_eq!(rec.cutoff_risk, 0); // infinity is not < hrs_left
        }

        #[test]
        fn bind_and_safe_w_default() {
            let now = base_now();
            let reset = reset_5h_from(now);
            let rec = compute_window_forecast("seven_day", 70.0, 90.0, reset, now, 1.0, true);

            assert_eq!(rec.bind, 0);
            assert!(rec.safe_w.is_none());
        }

        #[test]
        fn record_type_and_window_name() {
            let now = base_now();
            let reset = reset_5h_from(now);
            let rec = compute_window_forecast("seven_day_sonnet", 80.0, 90.0, reset, now, 1.0, false);

            assert_eq!(rec.r, "w");
            assert_eq!(rec.win, "seven_day_sonnet");
            assert_eq!(rec.pk, false);
        }

        #[test]
        fn five_hour_binding_over_seven_day() {
            // 5h window: margin_hrs = -2 (more constrained)
            // 7d window: margin_hrs = +5 (less constrained)
            let now = base_now();
            let mut forecasts = vec![
                compute_window_forecast("five_hour", 36.0, 90.0, now + Duration::hours(3), now, 30.0, false),
                compute_window_forecast("seven_day", 36.0, 90.0, now + Duration::hours(100), now, 2.0, false),
            ];

            // Before: both bind=0
            assert_eq!(forecasts[0].bind, 0);
            assert_eq!(forecasts[1].bind, 0);

            find_binding_window(&mut forecasts, 1.0);

            // five_hour should be binding (margin_hrs most negative)
            assert_eq!(forecasts[0].win, "five_hour");
            assert_eq!(forecasts[0].bind, 1);
            assert!(forecasts[0].safe_w.is_some());
            assert_eq!(forecasts[1].bind, 0);
            assert!(forecasts[1].safe_w.is_none());
        }

        #[test]
        fn seven_day_sonnet_binding() {
            let now = base_now();
            let mut forecasts = vec![
                compute_window_forecast("five_hour", 30.0, 90.0, now + Duration::hours(4), now, 1.0, false),
                compute_window_forecast("seven_day", 30.0, 90.0, now + Duration::hours(100), now, 0.5, false),
                compute_window_forecast("seven_day_sonnet", 85.0, 90.0, now + Duration::hours(50), now, 0.2, false),
            ];

            find_binding_window(&mut forecasts, 1.0);

            // seven_day_sonnet has remain=5, fleet_pct_hr=0.2, exh_hrs=25, hrs_left=50, margin=25
            // five_hour: remain=60, exh_hrs=60, hrs_left=4, margin=-56
            // Actually five_hour is more constrained. Let me adjust.
            // five_hour: remain=60, fleet_pct_hr=1.0, exh_hrs=60, hrs_left=4, margin=-56
            // So five_hour should be binding
            assert_eq!(forecasts[0].bind, 1);
        }

        #[test]
        fn safe_w_computation() {
            // remaining=50, hrs_left=10, p75_rate=1.0 -> safe_w = floor(50 / (1.0 * 10)) = 5
            assert_eq!(compute_safe_workers(50.0, 10.0, 1.0), 5);
        }

        #[test]
        fn safe_w_floor_behavior() {
            // remaining=50, hrs_left=10, p75_rate=1.1 -> safe_w = floor(50 / 11) = 4
            assert_eq!(compute_safe_workers(50.0, 10.0, 1.1), 4);
        }

        #[test]
        fn safe_w_zero_rate_returns_max() {
            assert_eq!(compute_safe_workers(50.0, 10.0, 0.0), u32::MAX);
        }

        #[test]
        fn safe_w_zero_hours_returns_max() {
            assert_eq!(compute_safe_workers(50.0, 0.0, 1.0), u32::MAX);
        }

        #[test]
        fn compute_window_forecasts_returns_three_records() {
            let now = base_now();
            let windows = vec![
                ("five_hour", 36.0, now + Duration::hours(3)),
                ("seven_day", 68.0, now + Duration::hours(100)),
                ("seven_day_sonnet", 72.0, now + Duration::hours(80)),
            ];

            let forecasts = compute_window_forecasts(&windows, 90.0, now, 2.0, false, 1.0);

            assert_eq!(forecasts.len(), 3);
            assert_eq!(forecasts[0].win, "five_hour");
            assert_eq!(forecasts[1].win, "seven_day");
            assert_eq!(forecasts[2].win, "seven_day_sonnet");

            // Exactly one binding window
            let binding_count = forecasts.iter().filter(|f| f.bind == 1).count();
            assert_eq!(binding_count, 1);
        }

        #[test]
        fn serialization_uses_correct_field_names() {
            let now = base_now();
            let reset = reset_5h_from(now);
            let rec = compute_window_forecast("five_hour", 36.0, 90.0, reset, now, 2.0, true);

            let json = serde_json::to_value(&rec).unwrap();
            let obj = json.as_object().unwrap();

            assert_eq!(obj.get("r").unwrap().as_str().unwrap(), "w");
            assert_eq!(obj.get("win").unwrap().as_str().unwrap(), "five_hour");
            assert!(obj.get("pk").unwrap().as_bool().unwrap());
            assert_eq!(obj.get("ceil").unwrap().as_f64().unwrap(), 90.0);
            assert_eq!(obj.get("snap").unwrap().as_f64().unwrap(), 36.0);
            assert_eq!(obj.get("remain").unwrap().as_f64().unwrap(), 54.0);
            assert_eq!(obj.get("hrs_left").unwrap().as_f64().unwrap(), 3.0);
            assert_eq!(obj.get("fleet_pct_hr").unwrap().as_f64().unwrap(), 2.0);
            assert_eq!(obj.get("exh_hrs").unwrap().as_f64().unwrap(), 27.0);
            assert_eq!(obj.get("cutoff_risk").unwrap().as_u64().unwrap(), 0);
            assert_eq!(obj.get("margin_hrs").unwrap().as_f64().unwrap(), -24.0);
            assert_eq!(obj.get("bind").unwrap().as_u64().unwrap(), 0);
            // safe_w is None and should be omitted from serialization
            assert!(!obj.contains_key("safe_w"));
        }
    }

    // --- Instance record tests (bead docs-lfz) ---

    mod instance {
        use super::*;
        use chrono::{Duration, Utc};

        fn ts(s: &str) -> DateTime<Utc> {
            s.parse().unwrap()
        }

        fn make_instance(
            sess: &str,
            model: &str,
            input_n: u64,
            output_n: u64,
            r_cache_n: u64,
            w_cache_n: u64,
            w_cache_1h_n: u64,
            total_usd: f64,
            t0: DateTime<Utc>,
        ) -> InstanceRecord {
            InstanceRecord {
                r: "i".to_string(),
                ts: t0 + Duration::minutes(5),
                t0,
                t1: t0 + Duration::minutes(5),
                sess: sess.to_string(),
                sid: sess.to_string(),
                model: model.to_string(),
                pk: if is_peak(t0) { 1 } else { 0 },
                hr_et: hr_et(t0),
                dow: dow(t0),
                input_n,
                input_usd: input_n as f64 * 0.003,
                output_n,
                output_usd: output_n as f64 * 0.015,
                r_cache_n,
                r_cache_usd: r_cache_n as f64 * 0.0003,
                w_cache_n,
                w_cache_usd: w_cache_n as f64 * 0.00375,
                w_cache_1h_n,
                w_cache_1h_usd: w_cache_1h_n as f64 * 0.006,
                total_usd,
                cache_eff: {
                    let total_input = input_n + r_cache_n;
                    if total_input > 0 { r_cache_n as f64 / total_input as f64 } else { 0.0 }
                },
                p5h: None,
                p7d: None,
                p7ds: None,
            }
        }

        #[test]
        fn serialization_has_correct_field_names() {
            // March 18 2026 is a Wednesday; 14:00 UTC = 10:00 ET (EDT, UTC-4)
            let t0 = ts("2026-03-18T14:00:00Z");
            let rec = make_instance("sess-1", "claude-sonnet-4-20250514", 1000, 500, 200, 100, 50, 0.05, t0);

            let json = serde_json::to_value(&rec).unwrap();
            let obj = json.as_object().unwrap();

            assert_eq!(obj.get("r").unwrap().as_str().unwrap(), "i");
            assert_eq!(obj.get("sess").unwrap().as_str().unwrap(), "sess-1");
            assert_eq!(obj.get("sid").unwrap().as_str().unwrap(), "sess-1");
            assert_eq!(obj.get("model").unwrap().as_str().unwrap(), "claude-sonnet-4-20250514");
            assert_eq!(obj.get("pk").unwrap().as_u64().unwrap(), 1);
            assert_eq!(obj.get("hr_et").unwrap().as_u64().unwrap(), 10);
            assert_eq!(obj.get("dow").unwrap().as_u64().unwrap(), 2); // Wed
            assert_eq!(obj.get("input-n").unwrap().as_u64().unwrap(), 1000);
            assert_eq!(obj.get("output-n").unwrap().as_u64().unwrap(), 500);
            assert_eq!(obj.get("r-cache-n").unwrap().as_u64().unwrap(), 200);
            assert_eq!(obj.get("w-cache-n").unwrap().as_u64().unwrap(), 100);
            assert_eq!(obj.get("w-cache-1h-n").unwrap().as_u64().unwrap(), 50);
            assert!((obj.get("total-usd").unwrap().as_f64().unwrap() - 0.05).abs() < 1e-9);

            // Window fields are None → should be omitted from serialization
            assert!(!obj.contains_key("p5h"));
            assert!(!obj.contains_key("p7d"));
            assert!(!obj.contains_key("p7ds"));
        }

        #[test]
        fn new_from_usage_and_dollars() {
            let t0 = ts("2026-03-18T14:00:00Z");
            let usage = UsageRecord {
                input_tokens: 1000,
                output_tokens: 500,
                cache_read_tokens: 200,
                cache_write_5m_tokens: 100,
                cache_write_1h_tokens: 50,
                model: "claude-sonnet-4-20250514".to_string(),
                session: "test-session".to_string(),
            };
            let dollars = crate::pricing::DollarBreakdown {
                input_usd: 3.0,
                output_usd: 7.5,
                cache_read_usd: 0.06,
                cache_write_5m_usd: 0.375,
                cache_write_1h_usd: 0.3,
                total_usd: 11.235,
            };

            let rec = InstanceRecord::new(
                t0 + Duration::minutes(5),
                t0,
                t0 + Duration::minutes(5),
                "test-session".to_string(),
                "sid-abc".to_string(),
                "claude-sonnet-4-20250514".to_string(),
                &usage,
                &dollars,
            );

            assert_eq!(rec.r, "i");
            assert_eq!(rec.input_n, 1000);
            assert_eq!(rec.output_n, 500);
            assert_eq!(rec.total_usd, 11.235);
            assert_eq!(rec.pk, 1); // 10am ET Wednesday = peak
        }
    }

    // --- Fleet record tests (bead docs-lfz) ---

    mod fleet {
        use super::*;
        use chrono::{Duration, Utc};

        fn ts(s: &str) -> DateTime<Utc> {
            s.parse().unwrap()
        }

        fn make_instance(
            sess: &str,
            model: &str,
            input_n: u64,
            total_usd: f64,
            t0: DateTime<Utc>,
        ) -> InstanceRecord {
            InstanceRecord {
                r: "i".to_string(),
                ts: t0 + Duration::minutes(5),
                t0,
                t1: t0 + Duration::minutes(5),
                sess: sess.to_string(),
                sid: sess.to_string(),
                model: model.to_string(),
                pk: if is_peak(t0) { 1 } else { 0 },
                hr_et: hr_et(t0),
                dow: dow(t0),
                input_n,
                input_usd: input_n as f64 * 0.003,
                output_n: input_n / 2,
                output_usd: (input_n / 2) as f64 * 0.015,
                r_cache_n: 0,
                r_cache_usd: 0.0,
                w_cache_n: 0,
                w_cache_usd: 0.0,
                w_cache_1h_n: 0,
                w_cache_1h_usd: 0.0,
                total_usd,
                cache_eff: 0.0,
                p5h: None,
                p7d: None,
                p7ds: None,
            }
        }

        #[test]
        fn aggregation_sums_two_instances() {
            let t0 = ts("2026-03-18T14:00:00Z"); // Wed 10am ET, peak
            let t1 = t0 + Duration::minutes(5);
            let all_models = vec!["claude-sonnet-4-20250514".to_string()];

            let inst1 = make_instance("worker-a", "claude-sonnet-4-20250514", 1000, 0.05, t0);
            let inst2 = make_instance("worker-b", "claude-sonnet-4-20250514", 2000, 0.10, t0);

            let fleet = aggregate_to_fleet(
                &[inst1, inst2],
                t1,
                t0,
                t1,
                &all_models,
            );

            assert_eq!(fleet.workers, 2);
            assert_eq!(fleet.pk, 1);
            assert!((fleet.total_usd - 0.15).abs() < 1e-9);

            // Per-model columns should sum
            let sonnet_tok = fleet.model_data.iter().find(|(m, _)| m == "claude-sonnet-4-20250514").unwrap();
            assert_eq!(sonnet_tok.1.input_n, 3000); // 1000 + 2000
        }

        #[test]
        fn p75_and_stddev_with_three_instances() {
            let t0 = ts("2026-03-18T14:00:00Z");
            let t1 = t0 + Duration::hours(1); // 1 hour interval
            let all_models = vec!["claude-sonnet-4-20250514".to_string()];

            // USD/hr: 1.0, 2.0, 3.0
            let inst1 = make_instance("a", "claude-sonnet-4-20250514", 100, 1.0, t0);
            let inst2 = make_instance("b", "claude-sonnet-4-20250514", 100, 2.0, t0);
            let inst3 = make_instance("c", "claude-sonnet-4-20250514", 100, 3.0, t0);

            let fleet = aggregate_to_fleet(
                &[inst1, inst2, inst3],
                t1,
                t0,
                t1,
                &all_models,
            );

            // p75 nearest-rank: n=3, ceil(3*0.75)-1 = ceil(2.25)-1 = 3-1 = 2 → rates[2] = 3.0
            assert_eq!(fleet.p75_usd_hr, 3.0);

            // stddev: mean=2.0, var=((1-2)^2+(2-2)^2+(3-2)^2)/3 = 2/3, std=0.8165...
            let expected_std = (2.0_f64 / 3.0).sqrt();
            assert!(
                (fleet.std_usd_hr - expected_std).abs() < 1e-9,
                "expected stddev={}, got {}",
                expected_std,
                fleet.std_usd_hr
            );
        }

        #[test]
        fn zero_activity_models_zero_filled() {
            let t0 = ts("2026-03-18T14:00:00Z");
            let t1 = t0 + Duration::minutes(5);
            let all_models = vec![
                "claude-sonnet-4-20250514".to_string(),
                "claude-opus-4-20250514".to_string(),
                "claude-haiku-4-5-20251001".to_string(),
            ];

            // Only sonnet has activity
            let inst = make_instance("a", "claude-sonnet-4-20250514", 500, 0.02, t0);

            let fleet = aggregate_to_fleet(&[inst], t1, t0, t1, &all_models);

            assert_eq!(fleet.model_data.len(), 3);

            let json = fleet.to_json_value();
            let obj = json.as_object().unwrap();

            // Opus should have zero-filled columns
            assert_eq!(obj.get("claude-opus-4-20250514-input-n").unwrap().as_u64().unwrap(), 0);
            assert_eq!(obj.get("claude-opus-4-20250514-input-usd").unwrap().as_f64().unwrap(), 0.0);
            assert_eq!(obj.get("claude-opus-4-20250514-output-n").unwrap().as_u64().unwrap(), 0);

            // Haiku should also be zero-filled
            assert_eq!(obj.get("claude-haiku-4-5-20251001-input-n").unwrap().as_u64().unwrap(), 0);

            // Sonnet should have actual data
            assert_eq!(obj.get("claude-sonnet-4-20250514-input-n").unwrap().as_u64().unwrap(), 500);
        }

        #[test]
        fn fleet_serialization_has_correct_shape() {
            let t0 = ts("2026-03-18T14:00:00Z");
            let t1 = t0 + Duration::minutes(5);
            let all_models = vec!["claude-sonnet-4-20250514".to_string()];

            let inst = make_instance("a", "claude-sonnet-4-20250514", 100, 0.01, t0);
            let fleet = aggregate_to_fleet(&[inst], t1, t0, t1, &all_models);

            let json = fleet.to_json_value();
            let obj = json.as_object().unwrap();

            assert_eq!(obj.get("r").unwrap().as_str().unwrap(), "f");
            assert_eq!(obj.get("pk").unwrap().as_u64().unwrap(), 1);
            assert_eq!(obj.get("hr_et").unwrap().as_u64().unwrap(), 10);
            assert_eq!(obj.get("dow").unwrap().as_u64().unwrap(), 2);
            assert_eq!(obj.get("workers").unwrap().as_u64().unwrap(), 1);
            assert!(obj.contains_key("total-usd"));
            assert!(obj.contains_key("p75-usd-hr"));
            assert!(obj.contains_key("std-usd-hr"));

            // Window snapshots should be null
            assert!(obj.get("p5h").unwrap().is_null());
            assert!(obj.get("p7d").unwrap().is_null());
            assert!(obj.get("p7ds").unwrap().is_null());
            assert!(obj.get("usd-per-pct-7ds").unwrap().is_null());
        }
    }

    // --- Peak detection tests (bead docs-lfz) ---

    mod peak {
        use super::*;
        use chrono::{Duration, Utc};

        fn ts(s: &str) -> DateTime<Utc> {
            s.parse().unwrap()
        }

        #[test]
        fn weekday_10am_et_is_peak() {
            // March 18 2026 is a Wednesday; 14:00 UTC = 10:00 ET (EDT)
            assert!(is_peak(ts("2026-03-18T14:00:00Z")));
        }

        #[test]
        fn weekday_3pm_et_is_off_peak() {
            // March 18 2026 is a Wednesday; 19:00 UTC = 15:00 ET (EDT) = 3pm
            assert!(!is_peak(ts("2026-03-18T19:00:00Z")));
        }

        #[test]
        fn weekend_10am_et_is_off_peak() {
            // March 21 2026 is a Saturday; 14:00 UTC = 10:00 ET
            assert!(!is_peak(ts("2026-03-21T14:00:00Z")));
        }

        #[test]
        fn weekday_8am_et_is_peak() {
            // March 18 2026 is a Wednesday; 12:00 UTC = 8:00 ET (EDT)
            assert!(is_peak(ts("2026-03-18T12:00:00Z")));
        }

        #[test]
        fn weekday_1pm_et_is_peak() {
            // March 18 2026 is a Wednesday; 17:00 UTC = 13:00 ET (EDT) = 1pm
            assert!(is_peak(ts("2026-03-18T17:00:00Z")));
        }

        #[test]
        fn weekday_2pm_et_is_off_peak() {
            // March 18 2026 is a Wednesday; 18:00 UTC = 14:00 ET (EDT) = 2pm (exclusive)
            assert!(!is_peak(ts("2026-03-18T18:00:00Z")));
        }

        #[test]
        fn hr_et_and_dow_correct() {
            // March 18 2026 is a Wednesday; 14:00 UTC = 10:00 ET
            assert_eq!(hr_et(ts("2026-03-18T14:00:00Z")), 10);
            assert_eq!(dow(ts("2026-03-18T14:00:00Z")), 2); // Wed

            // March 16 2026 is a Monday
            assert_eq!(dow(ts("2026-03-16T14:00:00Z")), 0);

            // March 22 2026 is a Sunday
            assert_eq!(dow(ts("2026-03-22T14:00:00Z")), 6);
        }
    }

    // --- JSONL append tests (bead docs-lfz) ---

    mod jsonl_append {
        use super::*;

        #[test]
        fn writes_valid_jsonl() {
            let temp_dir = TempDir::new().unwrap();
            let path = temp_dir.path().join("test.jsonl");

            let records = vec![
                serde_json::json!({"r": "i", "sess": "a", "total-usd": 0.01}),
                serde_json::json!({"r": "i", "sess": "b", "total-usd": 0.02}),
            ];

            append_jsonl(&path, &records).unwrap();

            let content = fs::read_to_string(&path).unwrap();
            let lines: Vec<&str> = content.lines().collect();
            assert_eq!(lines.len(), 2);

            // Each line is valid JSON
            for line in &lines {
                let _: serde_json::Value = serde_json::from_str(line).unwrap();
            }
        }

        #[test]
        fn append_to_existing_file() {
            let temp_dir = TempDir::new().unwrap();
            let path = temp_dir.path().join("test.jsonl");

            // Write first record
            let records1 = vec![serde_json::json!({"r": "i", "sess": "a"})];
            append_jsonl(&path, &records1).unwrap();

            // Append second record
            let records2 = vec![serde_json::json!({"r": "i", "sess": "b"})];
            append_jsonl(&path, &records2).unwrap();

            let content = fs::read_to_string(&path).unwrap();
            let lines: Vec<&str> = content.lines().collect();
            assert_eq!(lines.len(), 2);

            // First record preserved
            let first: serde_json::Value = serde_json::from_str(lines[0]).unwrap();
            assert_eq!(first["sess"], "a");

            // Second record appended
            let second: serde_json::Value = serde_json::from_str(lines[1]).unwrap();
            assert_eq!(second["sess"], "b");
        }

        #[test]
        fn empty_records_writes_nothing() {
            let temp_dir = TempDir::new().unwrap();
            let path = temp_dir.path().join("test.jsonl");

            append_jsonl(&path, &[]).unwrap();

            assert!(!path.exists());
        }

        #[test]
        fn creates_parent_directories() {
            let temp_dir = TempDir::new().unwrap();
            let path = temp_dir.path().join("nested").join("dir").join("test.jsonl");

            let records = vec![serde_json::json!({"r": "i"})];
            append_jsonl(&path, &records).unwrap();

            assert!(path.exists());
        }
    }
}
