//! Token Collector - reads Claude Code JSONL session files and extracts usage data
//!
//! This module handles:
//! - Walking ~/.claude/projects/**/*.jsonl to find session files
//! - Parsing usage blocks from assistant messages
//! - Tracking per-model token usage by type

use serde::Deserialize;

/// Usage record extracted from a Claude Code JSONL assistant message
///
/// Contains token counts for all five token types used in Claude API pricing:
/// - Input tokens: prompt tokens sent to the model
/// - Output tokens: tokens generated by the model
/// - Cache read tokens: cached prompt tokens read
/// - Cache write (5m) tokens: prompt tokens written to 5-minute cache
/// - Cache write (1h) tokens: prompt tokens written to 1-hour cache
#[derive(Debug, Clone, PartialEq)]
pub struct UsageRecord {
    /// Input prompt tokens
    pub input_tokens: u64,

    /// Output generation tokens
    pub output_tokens: u64,

    /// Cached prompt tokens that were read from cache
    pub cache_read_tokens: u64,

    /// Prompt tokens written to 5-minute ephemeral cache
    pub cache_write_5m_tokens: u64,

    /// Prompt tokens written to 1-hour ephemeral cache
    pub cache_write_1h_tokens: u64,

    /// Model identifier (e.g., "claude-sonnet-4-20250514")
    pub model: String,

    /// Session identifier (extracted from JSONL file path)
    pub session: String,
}

impl UsageRecord {
    /// Create a new zero-initialized UsageRecord
    pub fn zero(model: String, session: String) -> Self {
        Self {
            input_tokens: 0,
            output_tokens: 0,
            cache_read_tokens: 0,
            cache_write_5m_tokens: 0,
            cache_write_1h_tokens: 0,
            model,
            session,
        }
    }

    /// Get the total tokens used (all types combined)
    pub fn total_tokens(&self) -> u64 {
        self.input_tokens
            + self.output_tokens
            + self.cache_read_tokens
            + self.cache_write_5m_tokens
            + self.cache_write_1h_tokens
    }

    /// Check if this is a zero record (no tokens used)
    pub fn is_zero(&self) -> bool {
        self.total_tokens() == 0
    }
}

/// Raw usage block from a Claude API response
#[derive(Debug, Deserialize)]
pub struct ApiUsage {
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_creation_input_tokens: Option<u64>,
    pub cache_read_input_tokens: Option<u64>,
    pub cache_creation: Option<CacheCreation>,
}

/// Cache creation breakdown (nested in usage block)
#[derive(Debug, Deserialize)]
pub struct CacheCreation {
    pub ephemeral_5m_input_tokens: Option<u64>,
    pub ephemeral_1h_input_tokens: Option<u64>,
}

/// Assistant message from Claude Code JSONL
#[derive(Debug, Deserialize)]
pub struct AssistantMessage {
    pub usage: Option<ApiUsage>,
    pub model: Option<String>,
}

/// JSONL line (can be various message types)
#[derive(Debug, Deserialize)]
pub struct JsonlLine {
    #[serde(rename = "type")]
    pub msg_type: Option<String>,
    pub message: Option<AssistantMessage>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_usage_record_zero() {
        let record = UsageRecord::zero("test-model".to_string(), "test-session".to_string());
        assert_eq!(record.total_tokens(), 0);
        assert!(record.is_zero());
    }

    #[test]
    fn test_usage_record_total() {
        let record = UsageRecord {
            input_tokens: 1000,
            output_tokens: 500,
            cache_read_tokens: 200,
            cache_write_5m_tokens: 100,
            cache_write_1h_tokens: 50,
            model: "test".to_string(),
            session: "session".to_string(),
        };
        assert_eq!(record.total_tokens(), 1850);
        assert!(!record.is_zero());
    }

    #[test]
    fn test_parse_jsonl_usage() {
        let json = r#"{"type":"message","message":{"role":"assistant","content":[],"model":"claude-sonnet-4-20250514","usage":{"input_tokens":1000,"output_tokens":500,"cache_creation_input_tokens":100,"cache_read_input_tokens":50,"cache_creation":{"ephemeral_5m_input_tokens":50,"ephemeral_1h_input_tokens":50}}}}"#;

        let line: JsonlLine = serde_json::from_str(json).unwrap();
        assert_eq!(line.msg_type, Some("message".to_string()));

        let msg = line.message.unwrap();
        assert_eq!(msg.model, Some("claude-sonnet-4-20250514".to_string()));

        let usage = msg.usage.unwrap();
        assert_eq!(usage.input_tokens, 1000);
        assert_eq!(usage.output_tokens, 500);
        assert_eq!(usage.cache_creation_input_tokens, Some(100));
        assert_eq!(usage.cache_read_input_tokens, Some(50));

        let cache_creation = usage.cache_creation.unwrap();
        assert_eq!(cache_creation.ephemeral_5m_input_tokens, Some(50));
        assert_eq!(cache_creation.ephemeral_1h_input_tokens, Some(50));
    }
}
